name: test-fs

on: [push]

jobs:
  test-fs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up as module
      run: |
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/organizations
        npm install -g mocha
        rm -rf node_modules/@userdashboard/organizations/src
        rm -rf node_modules/@userdashboard/organizations/languages
        cp /home/runner/work/organizations/organizations/*.js node_modules/@userdashboard/organizations
        cp -R /home/runner/work/organizations/organizations/languages/ node_modules/@userdashboard/organizations/languages/
        cp -R /home/runner/work/organizations/organizations/src/ node_modules/@userdashboard/organizations/src/
        echo "global.applicationPath = __dirname" > main.js
        PACKAGE=`cat package.json`
        PACKAGE=${PACKAGE/\"description\"\: \"\"/\"dashboard\": \{ \"modules\"\: \[\"@userdashboard/organizations\"\] \}}
        echo $PACKAGE > package.json
    - name: Test unencrypted file-system storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test encrypted file-system storage
      run: mocha --retries 2 --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
      working-directory: "/tmp/project"
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"